[package]
name = "todo_list"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "todo_list_lib"
path = "src/lib.rs"

[[bin]]
name = "todo_list"
path = "src/main.rs"

[dependencies]
chrono = "0.4.38"
